[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "camera=*, microphone=*"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"
